language: node_js
node_js:
  - '0.12'
sudo: false
notifications:
  slack: solaryetsofar:oh0tLw34OZvc8WK5t5MgeGKp
cache:
  directories:
    - node_modules
    - app/bower_components
before_script:
  - 'npm i -g bower gulp'
  - 'npm i' # install npm packages
  - 'bower i' # install bower packages
after_script:
  - 'npm run release' # package the UI
