language: node_js
node_js:
  - '0.10'
sudo: false
notifications:
  slack: solaryetsofar:oh0tLw34OZvc8WK5t5MgeGKp
cache:
  directories:
    - node_modules
    - app/bower_components
before_script:
  - 'npm install -g bower gulp'
  - 'npm install' # install npm packages
  - 'bower install' # install bower packages
after_script:
  - 'gulp build-GUI' # package the UI