/**
 * Created by Bouse on 01/23/2015
 */

(function () {

  'use strict';

  angular.module('sicklifes')

    .factory('dataRecovery', function () {

      var dataRecovery = {};

      dataRecovery.draftOrder = {
        chester: [
          'Diego COSTA',
          'Paulo DYBALA',
          'Stevan JOVETIC',
          'Jackson MARTINEZ',
          'Romelu LUKAKU',
          'Carlos BACCA',
          'Daniele BASELLI',
          'Franco VAZQUEZ',
          'Callum WILSON',
          'Ayoze PEREZ',
          'Steven NAISMITH',
          'Jose Salomon RONDON',
          'Leo BAPTISTAO',
          'Imanol AGIRRETXE',
          'Leonardo ULLOA',
          'Iker MUNIAIN',
          'Bastian SCHWEINSTEIGER',
          'Giuseppe ROSSI',
          'Jeremy MENEZ',
          'Philippe COUTINHO',
          'Douglas COSTA',
          'Valter BIRSA',
          'CHARLES',
          'Scott SINCLAIR',
          'Odion IGHALO',
          'Inaki WILLIAMS',
          'Roberto FIRMINO',
          'MBaye NIANG',
          'Alvaro NEGREDO'
        ],
        frank: [
          'NEYMAR',
          'Antoine GRIEZMANN',
          'Gonzalo HIGUAIN',
          'Mauro ICARDI',
          'Bafetimbi GOMIS',
          'NOLITO',
          'Ruben CASTRO',
          'Luca TONI',
          'Fernando TORRES',
          'Antonio DI NATALE',
          'Theo WALCOTT',
          'Zlatan IBRAHIMOVIC',
          'Mario BALOTELLI',
          'David SILVA',
          'Marek HAMSIK',
          'Luciano VIETTO',
          'German DENIS',
          'Rudy GESTEDE',
          'Jeremain LENS',
          'Jesse LINGARD',
          'LUCAS PEREZ',
          'Josip ILICIC',
          'KOKE',
          'Jay RODRIGUEZ',
          'Ryan MASON',
          'Miralem PJANIC',
          'Georginio WIJNALDUM',
          'WILLIAN'
        ],
        joe: [
          'Cristiano RONALDO',
          'Alexis SANCHEZ',
          'James RODRIGUEZ',
          'Aritz ADURIZ',
          'Wilfried BONY',
          'Memphis DEPAY',
          'Jose Maria CALLEJON',
          'Kevin GAMEIRO',
          'Saido BERAHINO',
          'Manolo GABBIADINI',
          'Robert LEWANDOWSKI',
          'Domenico BERARDI',
          'Mikel ARRUABARRENA',
          'Daniel PAREJO',
          'Riyad MAHREZ',
          'Ricardo KISHNA',
          'Danny INGS',
          'Antonio FLORO FLORES',
          'Papiss CISSE',
          'Franco BRIENZA',
          'OSCAR',
          'Cheikhou KOUYATE',
          'Ivan RAKITIC',
          'Ruben ROCHINA',
          'Borja BASTON',
          'Leonardo PAVOLETTI',
          'Antonio CANDREVA',
          'JOZABED'
        ],
        justin: [
          'Lionel MESSI',
          'Wayne ROONEY',
          'Olivier GIROUD',
          'Mario MANDZUKIC',
          'Harry KANE',
          'Ciro IMMOBILE',
          'Eden HAZARD',
          'Paco ALCACER',
          'Luiz ADRIANO',
          'Juan MATA',
          'Iago FALQUE',
          'Mario GOTZE',
          'Carlos VELA',
          'Lorenzo INSIGNE',
          'JONATHAS',
          'Nordin AMRABAT',
          'Andre AYEW',
          'Duvan ZAPATA',
          'Massimo MACCARONE',
          'Keita BALDE',
          'Jamie VARDY',
          'RODRIGO',
          'Gregoire DEFREL',
          'Marko ARNAUTOVIC',
          'Antonio SANABRIA',
          'Javi GUERRA',
          'Yohan CABAYE',
          'Massimo MACCARONE'
        ],
        mike: [
          'Luis SUAREZ',
          'Gareth BALE',
          'Edin DZEKO',
          'Christian BENTEKE',
          'Roberto SOLDADO',
          'Alvaro NEGREDO',
          'Andrea BELOTTI',
          'Thomas MULLER',
          'Fabio QUAGLIARELLA',
          'Radamel FALCAO',
          'Raheem STERLING',
          'Mame DIOUF',
          'Nikola KALINIC',
          'Felipe CAICEDO',
          'Diafra SAKHO',
          'Youssef EL ARABI',
          'Christian ERIKSEN',
          'Luis MURIEL',
          'Mattia DESTRO',
          'Mauricio PINILLA',
          'Paul POGBA',
          'Iago ASPAS',
          'Anthony MARTIAL',
          'Alessandro MATRI',
          'Alberto GILARDINO',
          'Kevin DE BRUYNE',
          'Raul GARCIA',
          'Troy DEENEY',
          'Andrea BELOTTI'
        ],
        dan: [
          'Sergio AGUERO',
          'Karim BENZEMA',
          'EDER',
          'Fernando LLORENTE',
          'Alvaro MORATA',
          'Yaya TOURE',
          'PEDRO',
          'Alberto PALOSCHI',
          'Graziano PELLE',
          'Jermain DEFOE',
          'Alvaro VAZQUEZ',
          'Cedric BAKAMBU',
          'Edinson CAVANI',
          'Felipe ANDERSON',
          'HERNANES',
          'Adrian GONZALEZ',
          'Riccardo SAPONARA',
          'Goran PANDEV',
          'Mohamed SALAH',
          'Cyril THEREAU',
          'ISCO',
          'Xherdan SHAQIRI',
          'Claudio MARCHISIO',
          'Arturo VIDAL',
          'GERVINHO',
          'Khouma BABACAR',
          'Ross BARKLEY',
          'Stephan EL SHAARAWY'
        ]
      };

      return dataRecovery;

    });

})();
